OutOfOffice.Web/Controllers/LeaveRequestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OutOfOffice.DataAccess.Data;
using OutOfOffice.Models;
using OutOfOffice.Models.ViewModels;
using System.Security.Claims;

namespace OutOfOffice.Web.Controllers
{
    public class LeaveRequestController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LeaveRequestController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin,HR manager,Project manager,Employee")]
        public IActionResult Index()
        {
            List<LeaveRequest> leaveRequests;
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (User.IsInRole("Admin"))
            {
                leaveRequests = _context.LeaveRequest.Include("Employee").ToList();
            }
            else if (User.IsInRole("HR manager"))
            {
                leaveRequests = new();
                IEnumerable<Employee> subordinates = _context.Employee
                    .Include("LeaveRequests")
                    .Where(s => s.PeoplePartnerId == userId);
                foreach (var s in subordinates)
                    s.LeaveRequests.ForEach(lr => leaveRequests.Add(lr));
            }   
            else if (User.IsInRole("Project manager"))
            {
                IEnumerable<Project> projects = 
                    _context.Project
                        .Include("Manager")
                        .Include("Members.LeaveRequests")
                        .Where(p => p.ManagerId == userId)
                        .ToList();
                List<Employee> subordinates = new();
                foreach (var p in projects)
                    p.Members.ForEach(m => { if (!subordinates.Contains(m)) subordinates.Add(m); });
                leaveRequests = new();
                foreach (var s in subordinates)
                    s.LeaveRequests.ForEach(lr => leaveRequests.Add(lr));
            }
            else
            {
                leaveRequests = _context.Employee
                    .Include("LeaveRequests")
                    .FirstOrDefault(e => e.Id == userId)
                    .LeaveRequests
                    .ToList();
            }
            
            return View(leaveRequests);
        }

        [Authorize(Roles = "Admin,Employee")]
        public IActionResult Upsert(int? id)
        {
            LeaveRequestVM leaveRequestVM = new();

            // create new entry
            if (id == null || id == 0)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                leaveRequestVM.LeaveRequest = new()
                {
                    EmployeeId = userId,
                    Employee = _context.Employee.Find(userId),
                    Status = "New"
                };
                
                return View(leaveRequestVM);
            }
            // update existing entry
            else
            {
                leaveRequestVM.LeaveRequest = _context.LeaveRequest.Include("Employee").FirstOrDefault(lr => lr.Id == id);
                if (leaveRequestVM.LeaveRequest == null)
                {
                    return NotFound();
                }
                return View(leaveRequestVM);
            }
        }

        [Authorize(Roles = "Admin,Employee")]
        [HttpPost]
        public IActionResult Upsert(LeaveRequestVM leaveRequestVM)
        {
            if (ModelState.IsValid)
            {
                leaveRequestVM.LeaveRequest.Employee = null;
                // updating existing entry
                var id = leaveRequestVM.LeaveRequest.Id;
                if (id != 0)
                {
                    _context.LeaveRequest.Update(leaveRequestVM.LeaveRequest);
                }
                // adding new entry
                else
                {
                    _context.LeaveRequest.Add(leaveRequestVM.LeaveRequest);
                }

                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return View(leaveRequestVM);
            }
        }

        [Authorize(Roles = "Admin,HR manager,Project manager,Employee")]
        public IActionResult Details(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            LeaveRequest leaveRequest = _context.LeaveRequest.Include("Employee").FirstOrDefault(lr => lr.Id == id);

            if (leaveRequest == null)
            {
                return NotFound();
            }

            return View(leaveRequest);
        }

        [Authorize(Roles = "Admin,Employee")]
        public IActionResult Submit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            LeaveRequest leaveRequest = _context.LeaveRequest.Include("Employee").FirstOrDefault(lr => lr.Id == id);
            leaveRequest.Status = "Submitted";

            LeaveRequestApproval leaveRequestApproval = new()
            {
                ApproverId = leaveRequest.Employee.PeoplePartnerId,
                LeaveRequestId = leaveRequest.Id,
                Status = "New"
            };

            _context.LeaveRequest.Update(leaveRequest);
            _context.LeaveRequestApproval.Add(leaveRequestApproval);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin,Employee")]
        public IActionResult Cancel(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            LeaveRequest leaveRequest = _context.LeaveRequest.Include("Employee").FirstOrDefault(lr => lr.Id == id);
            leaveRequest.Status = "Canceled";

            LeaveRequestApproval leaveRequestApproval = _context.LeaveRequestApproval.FirstOrDefault(lra => lra.LeaveRequestId == leaveRequest.Id);
            if (leaveRequestApproval != null) 
            {
                leaveRequestApproval.Status = "Canceled";
                _context.LeaveRequestApproval.Update(leaveRequestApproval);
            }

            _context.LeaveRequest.Update(leaveRequest);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

OutOfOffice.Web/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Build.Graph;
using Microsoft.EntityFrameworkCore;
using NuGet.Versioning;
using OutOfOffice.DataAccess.Data;
using OutOfOffice.Models;
using OutOfOffice.Models.ViewModels;
using System.Security.Claims;

namespace OutOfOffice.Web.Controllers
{
    public class ProjectController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProjectController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin,HR manager,Project manager,Employee")]
        public IActionResult Index()
        {
            List<Project> projects;
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (User.IsInRole("Admin"))
            {
                projects = _context.Project.Include("Manager").Include("Members").ToList();
            }
            else if (User.IsInRole("Project manager"))
            {
                projects = _context.Project
                    .Include("Manager")
                    .Include("Members")
                    .Where(p => p.ManagerId == userId)
                    .ToList();
            }
            else if (User.IsInRole("HR manager"))
            {
                projects = new List<Project>();
                IEnumerable<Employee> subordinates = _context.Employee
                    .Include("Projects.Manager")
                    .Where(e => e.PeoplePartnerId == userId)
                    .ToList();
                foreach (var s in subordinates)
                    s.Projects.ForEach(p => { if (!projects.Contains(p)) projects.Add(p); });
            }
            else
            {
                projects = _context.Employee
                    .Include("Projects.Manager")
                    .FirstOrDefault(e => e.Id == userId)
                    .Projects
                    .ToList();
            }
                        
            return View(projects);
        }

        [Authorize(Roles = "Admin,Project manager")]
        public IActionResult Upsert(int? id) 
        {
            ProjectVM projectVM = new();

            // getting the list of project managers out of db
            string roleName = "Project manager";

            var roleId = _context.Roles.FirstOrDefault(r => r.Name == roleName).Id;

            var managerIds = _context.UserRoles
                .Where(ur => ur.RoleId == roleId)
                .Select(ur => ur.UserId)
                .ToList();

            projectVM.ProjectManagerList = _context.Users
                .Where(u => managerIds.Contains(u.Id))
                .Select(u => new SelectListItem
                {
                    Text = u.FullName,
                    Value = u.Id.ToString()
                })
                .ToList();

            // getting the list of employees out of db
            roleName = "Employee";

            roleId = _context.Roles.FirstOrDefault(r => r.Name == roleName).Id;

            var employeeIds = _context.UserRoles
                .Where(ur => ur.RoleId == roleId)
                .Select(ur => ur.UserId)
                .ToList();

            projectVM.EmployeeList = _context.Users
                .Where(u => employeeIds.Contains(u.Id))
                .Select(u => new SelectListItem
                {
                    Text = u.FullName,
                    Value = u.Id.ToString()
                })
                .ToList();

            // create new entry
            if (id == null || id == 0)
            {
                projectVM.Project = new();
                return View(projectVM);
            }
            // update existing entry
            else
            {
                projectVM.Project = _context.Project.Include("Members").FirstOrDefault(p => p.Id == id);
                if (projectVM.Project == null)
                {
                    return NotFound();
                }
                projectVM.Project.Members.ForEach(x => projectVM.SelectedEmployees.Add(x.Id.ToString()));
                return View(projectVM);
            }
        }

        [Authorize(Roles = "Admin,Project manager")]
        [HttpPost]
        public IActionResult Upsert(ProjectVM projectVM)
        {
            // updating existing entry
            var id = projectVM.Project.Id;
            if (id != null && id != 0) 
            {
                var project = _context.Project.Include("Members").FirstOrDefault(p => p.Id == id);
                project.Type = projectVM.Project.Type;
                project.StartDate = projectVM.Project.StartDate;
                project.EndDate = projectVM.Project.EndDate;
                project.ManagerId = projectVM.Project.ManagerId;
                project.Comment = projectVM.Project.Comment;
                project.Status = projectVM.Project.Status;

                // removing existing connections from join table
                for (int i = project.Members.Count - 1; i >= 0; i--)
                {
                    project.Members.Remove(project.Members[i]);
                }

                // adding newly selected connections to join table
                foreach (string s in projectVM.SelectedEmployees)
                {
                    project.Members.Add(_context.Employee.FirstOrDefault(e => e.Id == s));
                }

                _context.Project.Update(project);
            }
            // adding new entry
            else
            {
                projectVM.Project.Members = new();

                // adding selected connetions to join table
                foreach (string s in projectVM.SelectedEmployees)
                {
                    projectVM.Project.Members.Add(_context.Employee.FirstOrDefault(e => e.Id == s));
                }

                _context.Project.Add(projectVM.Project);
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

OutOfOffice.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OutOfOffice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OutOfOffice.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OutOfOffice.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Lists
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" asp-controller="Employee" asp-action="Index">Employee</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-controller="Project" asp-action="Index">Project</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-controller="LeaveRequest" asp-action="Index">Leave Request</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-controller="LeaveRequestApproval" asp-action="Index">Leave Request Approval</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            Out of Office solution - Test Task
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>