OutOfOffice.Web/Controllers/LeaveRequestApprovalController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OutOfOffice.DataAccess.Data;
using OutOfOffice.Models;
using OutOfOffice.Models.ViewModels;
using System.Security.Claims;

namespace OutOfOffice.Web.Controllers
{
    public class LeaveRequestApprovalController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LeaveRequestApprovalController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin,HR manager,Project manager")]
        public IActionResult Index()
        {
            //List<LeaveRequest> leaveRequests;
            IEnumerable<LeaveRequestApproval> leaveRequestApprovals;
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (User.IsInRole("Admin"))
            {
                leaveRequestApprovals = _context.LeaveRequestApproval.Include("Approver").ToList();
            }
            else if (User.IsInRole("HR manager"))
            {
                List<int> lrIds = new();
                IEnumerable<Employee> subordinates = _context.Employee
                    .Include("LeaveRequests")
                    .Where(s => s.PeoplePartnerId == userId);
                foreach (var s in subordinates)
                    s.LeaveRequests.ForEach(lr => lrIds.Add(lr.Id));
                leaveRequestApprovals = _context.LeaveRequestApproval
                                            .Include("Approver")
                                            .Where(lra => lrIds.Contains(lra.LeaveRequestId))
                                            .ToList();
            }
            // project manager
            else 
            {
                IEnumerable<Project> projects =
                    _context.Project
                        .Include("Manager")
                        .Include("Members.LeaveRequests")
                        .Where(p => p.ManagerId == userId)
                        .ToList();
                List<Employee> subordinates = new();
                foreach (var p in projects)
                    p.Members.ForEach(m => { if (!subordinates.Contains(m)) subordinates.Add(m); });
                List<int> lrIds = new();
                foreach (var s in subordinates)
                    s.LeaveRequests.ForEach(lr => lrIds.Add(lr.Id));
                leaveRequestApprovals = _context.LeaveRequestApproval
                                            .Include("Approver")
                                            .Where(lra => lrIds.Contains(lra.LeaveRequestId))
                                            .ToList();
            }

            return View(leaveRequestApprovals);
        }

        [Authorize(Roles = "Admin,HR manager,Project manager")]
        public IActionResult Update(int? id) 
        {
            LeaveRequestApproval leaveRequestApproval = 
                _context.LeaveRequestApproval
                    .Include("LeaveRequest.Employee")
                    .FirstOrDefault(lra => lra.Id == id);
            leaveRequestApproval.ApproverId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            
            if (leaveRequestApproval == null)
            {
                return NotFound();
            }

            return View(leaveRequestApproval);
        }

        [Authorize(Roles = "Admin,HR manager,Project manager,Employee")]
        public IActionResult Details(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            LeaveRequestApproval lra = 
                _context.LeaveRequestApproval
                    .Include("Approver")
                    .FirstOrDefault(lra => lra.LeaveRequestId == id);

            if (lra == null)
            {
                return NotFound();
            }

            return View(lra);
        }

        [Authorize(Roles = "Admin,HR manager,Project manager")]
        [HttpPost]
        public IActionResult Approve(LeaveRequestApproval lra)
        {
            lra.Status = "Approved";
            
            LeaveRequest lr = _context.LeaveRequest.Include("Employee").FirstOrDefault(lr => lr.Id == lra.LeaveRequestId);
            lr.Status = "Approved";

            var totalDaysAbsence = lr.EndDate.Subtract(lr.StartDate).TotalDays;
            lr.Employee.OutOfOfficeBalance -= (int)totalDaysAbsence;
            
            _context.Employee.Update(lr.Employee);
            _context.LeaveRequest.Update(lr);
            _context.LeaveRequestApproval.Update(lra);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin,HR manager,Project manager")]
        [HttpPost]
        public IActionResult Reject(LeaveRequestApproval lra)
        {
            lra.Status = "Rejected";

            LeaveRequest lr = _context.LeaveRequest.Include("Employee").FirstOrDefault(lr => lr.Id == lra.LeaveRequestId);
            lr.Status = "Rejected";

            if (lr.Employee.OutOfOfficeBalance < 0)
            {
                return NotFound();
            }

            _context.LeaveRequest.Update(lr);
            _context.LeaveRequestApproval.Update(lra);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

OutOfOffice.Web/Controllers/LeaveRequestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OutOfOffice.DataAccess.Data;
using OutOfOffice.Models;
using OutOfOffice.Models.ViewModels;
using System.Security.Claims;

namespace OutOfOffice.Web.Controllers
{
    public class LeaveRequestController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LeaveRequestController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Admin,HR manager,Project manager,Employee")]
        public IActionResult Index()
        {
            List<LeaveRequest> leaveRequests;
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (User.IsInRole("Admin"))
            {
                leaveRequests = _context.LeaveRequest.Include("Employee").ToList();
            }
            else if (User.IsInRole("HR manager"))
            {
                leaveRequests = new();
                IEnumerable<Employee> subordinates = _context.Employee
                    .Include("LeaveRequests")
                    .Where(s => s.PeoplePartnerId == userId);
                foreach (var s in subordinates)
                    s.LeaveRequests.ForEach(lr => leaveRequests.Add(lr));
            }   
            else if (User.IsInRole("Project manager"))
            {
                IEnumerable<Project> projects = 
                    _context.Project
                        .Include("Manager")
                        .Include("Members.LeaveRequests")
                        .Where(p => p.ManagerId == userId)
                        .ToList();
                List<Employee> subordinates = new();
                foreach (var p in projects)
                    p.Members.ForEach(m => { if (!subordinates.Contains(m)) subordinates.Add(m); });
                leaveRequests = new();
                foreach (var s in subordinates)
                    s.LeaveRequests.ForEach(lr => leaveRequests.Add(lr));
            }
            else
            {
                leaveRequests = _context.Employee
                    .Include("LeaveRequests")
                    .FirstOrDefault(e => e.Id == userId)
                    .LeaveRequests
                    .ToList();
            }
            
            return View(leaveRequests);
        }

        [Authorize(Roles = "Admin,Employee")]
        public IActionResult Upsert(int? id)
        {
            LeaveRequestVM leaveRequestVM = new();

            // create new entry
            if (id == null || id == 0)
            {
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                leaveRequestVM.LeaveRequest = new()
                {
                    EmployeeId = userId,
                    Employee = _context.Employee.Find(userId),
                    Status = "New"
                };
                
                return View(leaveRequestVM);
            }
            // update existing entry
            else
            {
                leaveRequestVM.LeaveRequest = _context.LeaveRequest.Include("Employee").FirstOrDefault(lr => lr.Id == id);
                if (leaveRequestVM.LeaveRequest == null)
                {
                    return NotFound();
                }
                return View(leaveRequestVM);
            }
        }

        [Authorize(Roles = "Admin,Employee")]
        [HttpPost]
        public IActionResult Upsert(LeaveRequestVM leaveRequestVM)
        {
            if (ModelState.IsValid)
            {
                leaveRequestVM.LeaveRequest.Employee = null;
                // updating existing entry
                var id = leaveRequestVM.LeaveRequest.Id;
                if (id != 0)
                {
                    _context.LeaveRequest.Update(leaveRequestVM.LeaveRequest);
                }
                // adding new entry
                else
                {
                    _context.LeaveRequest.Add(leaveRequestVM.LeaveRequest);
                }

                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return View(leaveRequestVM);
            }
        }

        [Authorize(Roles = "Admin,HR manager,Project manager,Employee")]
        public IActionResult Details(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            LeaveRequest leaveRequest = _context.LeaveRequest.Include("Employee").FirstOrDefault(lr => lr.Id == id);

            if (leaveRequest == null)
            {
                return NotFound();
            }

            return View(leaveRequest);
        }

        [Authorize(Roles = "Admin,Employee")]
        public IActionResult Submit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            LeaveRequest leaveRequest = _context.LeaveRequest.Include("Employee").FirstOrDefault(lr => lr.Id == id);
            leaveRequest.Status = "Submitted";

            LeaveRequestApproval leaveRequestApproval = new()
            {
                ApproverId = leaveRequest.Employee.PeoplePartnerId,
                LeaveRequestId = leaveRequest.Id,
                Status = "New"
            };

            _context.LeaveRequest.Update(leaveRequest);
            _context.LeaveRequestApproval.Add(leaveRequestApproval);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin,Employee")]
        public IActionResult Cancel(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            LeaveRequest leaveRequest = _context.LeaveRequest.Include("Employee").FirstOrDefault(lr => lr.Id == id);
            leaveRequest.Status = "Canceled";

            LeaveRequestApproval leaveRequestApproval = _context.LeaveRequestApproval.FirstOrDefault(lra => lra.LeaveRequestId == leaveRequest.Id);
            if (leaveRequestApproval != null) 
            {
                leaveRequestApproval.Status = "Canceled";
                _context.LeaveRequestApproval.Update(leaveRequestApproval);
            }

            _context.LeaveRequest.Update(leaveRequest);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

OutOfOffice.Web/Views/LeaveRequestApproval/Details.cshtml
@model LeaveRequestApproval

@{
    ViewData["Title"] = "Leave Request Approval Details";
}

<h1>@ViewData["Title"]</h1>

<div class="row">
    <div class="col-md-6">
        <form>
            <div class="form-floating mb-3">
                <input asp-for="Approver.FullName" class="form-control" disabled />
                <label asp-for="Approver.FullName" class="ms-2">Approver Full Name</label>
            </div>
            <div class="form-floating mb-3">
                <textarea asp-for="Comment" class="form-control" style="height:125px" disabled></textarea>
                <label asp-for="Comment"></label>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Status" class="form-control" disabled />
                <label asp-for="Status" class="ms-2"></label>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

OutOfOffice.Web/Views/LeaveRequestApproval/Index.cshtml
@model List<LeaveRequestApproval>

@{
    ViewData["Title"] = "Leave Request Approvals";
}

<div class="container">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary">Leave Request Approval Table</h2>
        </div>
        <div class="col-6 text-end">
            @* <a asp-controller="LeaveRequestApproval" asp-action="Upsert" class="btn btn-primary btn-lg">
                <i class="bi bi-file-earmark-plus"></i>  Create
            </a> *@
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Approver</th>
                <th>Comment</th>
                <th>Status</th>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var lra in Model)
            {
                <tr>
                    <td>@lra.Approver?.FullName</td>
                    <td><small>@lra.Comment</small></td>
                    <td>@lra.Status</td>
                    <td>
                        @if (lra.Status == "New")
                        {
                            <a asp-controller="LeaveRequestApproval" asp-action="Update" asp-route-id="@lra.Id" class="btn btn-primary">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                        }
                        <a asp-controller="LeaveRequest" asp-action="Details" asp-route-id="@lra.LeaveRequestId" class="btn btn-info">
                            Details
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

OutOfOffice.Web/Views/LeaveRequestApproval/Update.cshtml
@model LeaveRequestApproval

@{
    ViewData["Title"] = "Leave Request Approval";
}

<h1>@ViewData["Title"]</h1>
Note that you will be saved as approver
<div class="row">
    <div class="col-md-6">
        <form method="post">
            <input asp-for="Id" hidden />
            <input asp-for="Status" hidden />
            <input asp-for="ApproverId" hidden />
            <input asp-for="LeaveRequestId" hidden />
            <div class="form-floating mb-3">
                <input asp-for="LeaveRequest.Employee.FullName" class="form-control" disabled />
                <label asp-for="LeaveRequest.Employee.FullName" class="ms-2"></label>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="LeaveRequest.AbsenceReason" class="form-control" disabled />
                <label asp-for="LeaveRequest.AbsenceReason" class="ms-2"></label>
            </div>
            <div class="form-floating mb-3">
                <input class="form-control" value="@Model.LeaveRequest.StartDate" disabled />
                <label asp-for="LeaveRequest.StartDate" class="ms-2">Start Date</label>
            </div>
            <div class="form-floating mb-3">
                <input value="@Model.LeaveRequest.EndDate" class="form-control" disabled />
                <label asp-for="LeaveRequest.EndDate" class="ms-2">EndDate</label>
            </div>
            <div class="form-floating mb-3">
                <textarea asp-for="LeaveRequest.Comment" class="form-control" style="height:125px" disabled></textarea>
                <label asp-for="LeaveRequest.Comment">Comment by @Model.LeaveRequest.Employee.FullName</label>
            </div>
            <div class="form-floating mb-3">
                <textarea asp-for="Comment" class="form-control" style="height:125px"></textarea>
                <label asp-for="Comment">Approver's comment</label>
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="row">
                <div class="col-3">
                    <button type="submit" asp-controller="LeaveRequestApproval" asp-action="Approve" class="btn btn-success btn-lg form-control">Approve</button>
                </div>
                <div class="col-3">
                    <button type="submit" asp-controller="LeaveRequestApproval" asp-action="Reject" class="btn btn-danger btn-lg form-control">Reject</button>
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <a asp-controller="LeaveRequestApproval" asp-action="Index" class="btn btn-secondary btn-lg form-control">Back to List</a>
                </div>
                <div class="col-3">
                    <a asp-controller="LeaveRequest" asp-action="Details" asp-route-id="@Model.LeaveRequestId" class="btn btn-info btn-lg form-control">Details</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}